"""Repository protocols — the seam between the engine and a storage backend.

A storage backend provides one class per repository plus a Store that bundles
them with transaction control. The engine depends only on these protocols.
"""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol

from pks.core.models import (
    KnowledgeObject,
    KnowledgeObjectType,
    KnowledgeObjectVersion,
    Provenance,
    Relationship,
    Resource,
    ResourceChunk,
    Workspace,
    WorkspaceRef,
    WorkspaceRefType,
)


class KnowledgeObjectRepository(Protocol):
    def insert(self, ko: KnowledgeObject) -> None: ...
    def get(self, ko_id: str) -> KnowledgeObject | None: ...
    def list(
        self,
        *,
        type: KnowledgeObjectType | None = None,
        name_contains: str | None = None,
    ) -> list[KnowledgeObject]: ...
    def update(self, ko: KnowledgeObject) -> None: ...
    def delete(self, ko_id: str) -> bool: ...
    def insert_version(self, version: KnowledgeObjectVersion) -> None: ...
    def list_versions(self, ko_id: str) -> list[KnowledgeObjectVersion]: ...


class RelationshipRepository(Protocol):
    def upsert(self, rel: Relationship) -> Relationship: ...
    def get(self, rel_id: str) -> Relationship | None: ...
    def delete(self, rel_id: str) -> bool: ...
    def list_for(self, ko_id: str) -> list[Relationship]: ...
    def list_all(self) -> list[Relationship]: ...


class ProvenanceRepository(Protocol):
    def insert(self, prov: Provenance) -> None: ...
    def list_for_knowledge_object(self, ko_id: str) -> list[Provenance]: ...
    def list_for_relationship(self, rel_id: str) -> list[Provenance]: ...
    def knowledge_object_ids_for_resource(self, resource_id: str) -> list[str]: ...


class ResourceRepository(Protocol):
    def insert(self, resource: Resource) -> None: ...
    def get(self, resource_id: str) -> Resource | None: ...
    def get_by_hash(self, content_hash: str) -> Resource | None: ...
    def list(self) -> list[Resource]: ...
    def update(self, resource: Resource) -> None: ...
    def replace_chunks(self, resource_id: str, chunks: list[ResourceChunk]) -> None: ...
    def list_chunks(self, resource_id: str) -> list[ResourceChunk]: ...
    def get_chunk(self, chunk_id: str) -> ResourceChunk | None: ...


class WorkspaceRepository(Protocol):
    def insert(self, workspace: Workspace) -> None: ...
    def get(self, workspace_id: str) -> Workspace | None: ...
    def get_by_name(self, name: str) -> Workspace | None: ...
    def list(self) -> list[Workspace]: ...
    def update(self, workspace: Workspace) -> None: ...
    def delete(self, workspace_id: str) -> bool: ...
    def add_ref(self, ref: WorkspaceRef) -> None: ...
    def remove_ref(
        self, workspace_id: str, object_type: WorkspaceRefType, object_id: str
    ) -> bool: ...
    def list_refs(self, workspace_id: str) -> list[WorkspaceRef]: ...


class Store(Protocol):
    knowledge_objects: KnowledgeObjectRepository
    relationships: RelationshipRepository
    provenance: ProvenanceRepository
    resources: ResourceRepository
    workspaces: WorkspaceRepository

    def transaction(self) -> AbstractContextManager[None]: ...
    def close(self) -> None: ...
